import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GoogleTranslate from "@/components/GoogleTranslate"; // Importando o novo componente
import { IdiomaProvider } from "@/context/IdiomaContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <IdiomaProvider> {/* 🔹 Agora, toda a aplicação tem acesso ao idioma */}
          {children}
        </IdiomaProvider>
        {/* Google Translate */}
        <GoogleTranslate />
      </body>
    </html>
  );
}
